### ISSUE TITLE
would the script be Apple M1 friendly?

### ISSUE THREAD

**Issue by chicman** [sczhou/CodeFormer#102]
PyTorch since supported M1 GPU with device = MPS , would you consider put the option into script?

**Comment by WebberShaw** [comment]
I tried to use it on my M1 MBP image processing seem work, but during video processing  output path doesn't have any result.

**Comment by sczhou** [comment]
Hi @WebberShaw , we have fixed this issue, you can pull the new update and check out our new commands for video enhancement. Note that:
```
# For Windows/Mac users, please install ffmpeg first
conda install -c conda-forge ffmpeg
```
If it still doesn't work, please re-install ffmpeg-python by running:
```
pip uninstall ffmpeg-python
pip install ffmpeg-python
```

**Comment by sczhou** [comment]
@chicman That sounds great, I will take a look at it and try to include it in the next update.

**Comment by sczhou** [comment]
@chicman Have updated to support M1 chip now!

**Comment by chicman** [comment]
Great. That all apple silicone gpu can work on this now.

**Comment by chicman** [comment]
Just tried the latest master on M1 gpu, here I got some missing modules.

(torch-gpu) ***@***.*** CodeFormerv3 % python inference_codeformer.py -w 0.5 --bg_upsampler realesrgan --input_path ./inputs/cropped_faces
Traceback (most recent call last):
 File "/Users/jm/miniconda3/CodeFormerv3/inference_codeformer.py", line 7, in <module>
 from basicsr.utils import imwrite, img2tensor, tensor2img
 File "/Users/jm/miniconda3/CodeFormerv3/basicsr/__init__.py", line 11, in <module>
 from .version import __gitsha__, __version__
ModuleNotFoundError: No module named 'basicsr.version'

**Comment by chicman** [comment]
OK never mind, just executed the basic/setup.py fixed the problem!

M1 GPU now works!

**Comment by a227799770055** [comment]
Dears, I want to ask how to use the m1 gpu in this project.

**Comment by beltonk** [comment]
I tried these, and able to accelerate with Apple Silicon (M1):

cd CoderFormer
python3 ./basicr/setup.py install
