### ISSUE TITLE
Background upsampling: False, Face upsampling: False

### ISSUE THREAD

**Issue by zhouqiw** [sczhou/CodeFormer#106]
Background upsampling: False, Face upsampling: False
Traceback (most recent call last):
  File "inference_codeformer.py", line 147, in <module>
    face_helper = FaceRestoreHelper(
  File "D:\github\CodeFormer-master\facelib\utils\face_restoration_helper.py", line 105, in __init__
    self.face_det = init_detection_model(det_model, half=False, device=self.device)
  File "D:\github\CodeFormer-master\facelib\detection\__init__.py", line 16, in init_detection_model
    model = init_retinaface_model(model_name, half, device)
  File "D:\github\CodeFormer-master\facelib\detection\__init__.py", line 36, in init_retinaface_model
    load_net = torch.load(model_path, map_location=lambda storage, loc: storage)
  File "D:\chengxu\ancanda\envs\py38\lib\site-packages\torch\serialization.py", line 795, in load
    return _legacy_load(opened_file, map_location, pickle_module, **pickle_load_args)
  File "D:\chengxu\ancanda\envs\py38\lib\site-packages\torch\serialization.py", line 1020, in _legacy_load
    typed_storage._storage._set_from_file(
RuntimeError: unexpected EOF, expected 7538569 more bytes. The file might be corrupted.

**Comment by sczhou** [comment]
`Background upsampling: False, Face upsampling: False` is your inference setting, not the error.
The error seems the pretrained model you downloaded is corrupted, please check it out or download again from:
https://github.com/sczhou/CodeFormer/releases/tag/v0.1.0
