### ISSUE TITLE
求助，第三个命令报错

### ISSUE THREAD

**Issue by ice5920** [sczhou/CodeFormer#129]
C:\Users\tl小站\CodeFormer>python basicsr/setup.py develop
Traceback (most recent call last):
  File "D:\rjanz\lib\site-packages\numpy\core\__init__.py", line 23, in <module>
    from . import multiarray
  File "D:\rjanz\lib\site-packages\numpy\core\multiarray.py", line 10, in <module>
    from . import overrides
  File "D:\rjanz\lib\site-packages\numpy\core\overrides.py", line 6, in <module>
    from numpy.core._multiarray_umath import (
ModuleNotFoundError: No module named 'numpy.core._multiarray_umath'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\tl小站\CodeFormer\basicsr\setup.py", line 9, in <module>
    from torch.utils.cpp_extension import BuildExtension, CppExtension, CUDAExtension
  File "D:\rjanz\lib\site-packages\torch\__init__.py", line 676, in <module>
    from .storage import _StorageBase, TypedStorage, _LegacyStorage, UntypedStorage
  File "D:\rjanz\lib\site-packages\torch\storage.py", line 11, in <module>
    import numpy as np
  File "D:\rjanz\lib\site-packages\numpy\__init__.py", line 141, in <module>
    from . import core
  File "D:\rjanz\lib\site-packages\numpy\core\__init__.py", line 49, in <module>
    raise ImportError(msg)
ImportError:

IMPORTANT: PLEASE READ THIS FOR ADVICE ON HOW TO SOLVE THIS ISSUE!

Importing the numpy C-extensions failed. This error can happen for
many reasons, often due to issues with your setup or how NumPy was
installed.

We have compiled some common reasons and troubleshooting tips at:

    https://numpy.org/devdocs/user/troubleshooting-importerror.html

Please note and check the following:

  * The Python version is: Python3.9 from "D:\rjanz\python.exe"
  * The NumPy version is: "1.24.1"

and make sure that they are the versions you expect.
Please carefully study the documentation linked above for further help.

Original error was: No module named 'numpy.core._multiarray_umath'

**Comment by sczhou** [comment]
Try to upgrade `numpy` by running:

```
pip install numpy --upgrade
```
