### ISSUE TITLE
Video: IndexError: list index out of range

### ISSUE THREAD

**Issue by sashaok123** [sczhou/CodeFormer#168]
An error occurs while trying to work with the video:
```
Traceback (most recent call last):
  File "inference_codeformer.py", line 7, in <module>
    from basicsr.utils import imwrite, img2tensor, tensor2img
  File "D:\AI\CodeFormer\basicsr\__init__.py", line 3, in <module>
    from .archs import *
  File "D:\AI\CodeFormer\basicsr\archs\__init__.py", line 5, in <module>
    from basicsr.utils import get_root_logger, scandir
  File "D:\AI\CodeFormer\basicsr\utils\__init__.py", line 4, in <module>
    from .misc import check_resume, get_time_str, make_exp_dirs, mkdir_and_rename, scandir, set_random_seed, sizeof_fmt
  File "D:\AI\CodeFormer\basicsr\utils\misc.py", line 12, in <module>
    IS_HIGH_VERSION = [int(m) for m in list(re.findall(r"^([0-9]+)\.([0-9]+)\.([0-9]+)([^0-9][a-zA-Z0-9]*)?(\+git.*)?$",\
IndexError: list index out of range
```
![image](https://user-images.githubusercontent.com/27728380/224223935-c7bfcc46-e9dc-4e8b-8a9e-76877de08c80.png)

**Comment by sciita** [comment]
Facing same issue

**Comment by Rayan-Alhindi** [comment]
I am facing the same issue, no solution yet?

**Comment by Lucca-cherries** [comment]
Try `pip install lpips`. This works for me.
