### ISSUE TITLE
Unable to start

### ISSUE THREAD

**Issue by bergstar** [sczhou/CodeFormer#177]
Following steps in installation guide gives this:
`(codeformer) C:\Users\HP\Development\CodeFormer>python basicsr/setup.py develop
python: can't open file 'basicsr/setup.py': [Errno 2] No such file or directory`

basicsr/ is there but has no setup.py file.

Downloading the models fail as well:
`(codeformer) C:\Users\HP\Development\CodeFormer>python scripts/download_pretrained_models.py facelib
Traceback (most recent call last):
  File "scripts/download_pretrained_models.py", line 5, in <module>
    from basicsr.utils.download_util import load_file_from_url
ModuleNotFoundError: No module named 'basicsr'`

Running a base test gives this error:
`(codeformer) C:\Users\HP\Development\CodeFormer>python inference_codeformer.py -w 0.5 --has_aligned --input_path input.png
Traceback (most recent call last):
  File "inference_codeformer.py", line 9, in <module>
    from basicsr.utils.misc import gpu_is_available, get_device
ImportError: cannot import name 'gpu_is_available' from 'basicsr.utils.misc' (C:\Users\HP\Development\CodeFormer\basicsr\utils\misc.py)`

**Comment by khak313** [comment]
same error and noclue how to solve
