### ISSUE TITLE
What is the reason for this error (video)

### ISSUE THREAD

**Issue by g558800** [sczhou/CodeFormer#187]
What is the reason for this error:
>python inference_codeformer.py --bg_upsampler realesrgan --face_upsample -w 1.0 --input_path .\30.mp4
Traceback (most recent call last):
  File "H:\AI\CodeFormer\inference_codeformer.py", line 93, in <module>
    vidreader = VideoReader(args.input_path)
  File "H:\AI\CodeFormer\basicsr\utils\video_util.py", line 35, in __init__
    ffmpeg.input(video_path).output('pipe:', format='rawvideo', pix_fmt='bgr24',
AttributeError: module 'ffmpeg' has no attribute 'input'

**Comment by codeyy2023** [comment]
I have the exact same problem as you, have you solved it yet?

**Comment by g558800** [comment]
not yet

**Comment by eloncarmo** [comment]
pip install ffmpeg-python

**Comment by YABIJIU** [comment]
> python inference_codeformer.py --bg_upsampler realesrgan --face_upsample -w 1.0 --input_path .\30.mp4
> Traceback (most recent call last):
> File "H:\AI\CodeFormer\inference_codeformer.py", line 93, in
> vidreader = VideoReader(args.input_path)
> File "H:\AI\CodeFormer\basicsr\utils\video_util.py", line 35, in **init**
> ffmpeg.input(video_path).output('pipe:', format='rawvideo', pix_fmt='bgr24',
> AttributeError: module 'ffmpeg' has no attribute 'input'



> pip install ffmpeg-python

IT     DOESN'T  WORK..

**Comment by miguelquinones12** [comment]
Any solution for this issue?
Thanks!
