### ISSUE TITLE
ImportError: cannot import name 'gaussian_kernels'

### ISSUE THREAD

**Issue by makaveli10** [sczhou/CodeFormer#205]
Hello @sczhou,
The most recent update caused this on colab.
To reproduce run this on colab:
```
# @title CodeFormer upsampling
!git clone https://github.com/sczhou/CodeFormer.git

import sys
sys.path.insert(0, "/content/CodeFormer")
!pip install -r CodeFormer/requirements.txt
%cd CodeFormer
!python basicsr/setup.py develop
%cd ..
!python CodeFormer/scripts/download_pretrained_models.py facelib
!python CodeFormer/scripts/download_pretrained_models.py CodeFormer
```

And I see that ```basics/setup.py``` runs successfully. But I cant download models because f the import error:
```
Traceback (most recent call last):
  File "/content/CodeFormer/scripts/download_pretrained_models.py", line 5, in <module>
    from basicsr.utils.download_util import load_file_from_url
  File "/content/CodeFormer/basicsr/__init__.py", line 4, in <module>
    from .data import *
  File "/content/CodeFormer/basicsr/data/__init__.py", line 22, in <module>
    _dataset_modules = [importlib.import_module(f'basicsr.data.{file_name}') for file_name in dataset_filenames]
  File "/content/CodeFormer/basicsr/data/__init__.py", line 22, in <listcomp>
    _dataset_modules = [importlib.import_module(f'basicsr.data.{file_name}') for file_name in dataset_filenames]
  File "/usr/lib/python3.9/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "/content/CodeFormer/basicsr/data/ffhq_blind_joint_dataset.py", line 12, in <module>
    from basicsr.data import gaussian_kernels as gaussian_kernels
ImportError: cannot import name 'gaussian_kernels' from partially initialized module 'basicsr.data' (most likely due to a circular import) (/content/CodeFormer/basicsr/data/__init__.py)
```

**Comment by xRoyBx** [comment]
Same problem here also using CodeFormer in "offline mode"

**Comment by Titukas22** [comment]
Ttry this:
Open the ffhq_blind_joint_dataset.py file in the CodeFormer-master\basicsr\data\ directory.

Comment out or remove the line that imports gaussian_kernels:
# import basicsr.data.gaussian_kernels as gaussian_kernels

Open the base_model.py file in the CodeFormer-master\basicsr\models\ directory.

Comment out or remove the line that imports lr_scheduler:
# import basicsr.models.lr_scheduler as lr_scheduler

**Comment by AloneMonologue** [comment]
can not import /CodeFormer/basicsr/data/__ init__   in /CodeFormer/basicsr/data/ffhq_blind_joint_dataset Gaussian_Kernels function
`Traceback (most recent call last):
  File "E:\File\Code\Python\Visual Studio\2022\CHZC\Software Cup\SoftwareCup PythonApplication\HELP\CodeFormer\inference_codeformer.py", line 7, in <module>
    from basicsr.utils import imwrite, img2tensor, tensor2img
  File "E:\File\Code\Python\Visual Studio\2022\CHZC\Software Cup\SoftwareCup PythonApplication\HELP\CodeFormer\basicsr\__init__.py", line 4, in <module>
    from .data import *
  File "E:\File\Code\Python\Visual Studio\2022\CHZC\Software Cup\SoftwareCup PythonApplication\HELP\CodeFormer\basicsr\data\__init__.py", line 22, in <module>
    _dataset_modules = [importlib.import_module(f'basicsr.data.{file_name}') for file_name in dataset_filenames]
  File "E:\File\Code\Python\Visual Studio\2022\CHZC\Software Cup\SoftwareCup PythonApplication\HELP\CodeFormer\basicsr\data\__init__.py", line 22, in <listcomp>
    _dataset_modules = [importlib.import_module(f'basicsr.data.{file_name}') for file_name in dataset_filenames]
  File "C:\Program Files\Python310\lib\importlib\__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "E:\File\Code\Python\Visual Studio\2022\CHZC\Software Cup\SoftwareCup PythonApplication\HELP\CodeFormer\basicsr\data\ffhq_blind_joint_dataset.py", line 12, in <module>
    from basicsr.data import gaussian_kernels as gaussian_kernels
ImportError: cannot import name 'gaussian_kernels' from partially initialized module 'basicsr.data' (most likely due to a circular import) (E:\File\Code\Python\Visual Studio\2022\CHZC\Software Cup\SoftwareCup PythonApplication\HELP\CodeFormer\basicsr\data\__init__.py)`

**Comment by AloneMonologue** [comment]
can not import /CodeFormer/basicsr/data/__ init__ in /CodeFormer/basicsr/data/ffhq_blind_joint_dataset Gaussian_Kernels function

> `Traceback (most recent call last):
  File "E:\File\Code\Python\Visual Studio\2022\CHZC\Software Cup\SoftwareCup PythonApplication\HELP\CodeFormer\inference_codeformer.py", line 7, in <module>
    from basicsr.utils import imwrite, img2tensor, tensor2img
  File "E:\File\Code\Python\Visual Studio\2022\CHZC\Software Cup\SoftwareCup PythonApplication\HELP\CodeFormer\basicsr\__init__.py", line 4, in <module>
    from .data import *
  File "E:\File\Code\Python\Visual Studio\2022\CHZC\Software Cup\SoftwareCup PythonApplication\HELP\CodeFormer\basicsr\data\__init__.py", line 22, in <module>
    _dataset_modules = [importlib.import_module(f'basicsr.data.{file_name}') for file_name in dataset_filenames]
  File "E:\File\Code\Python\Visual Studio\2022\CHZC\Software Cup\SoftwareCup PythonApplication\HELP\CodeFormer\basicsr\data\__init__.py", line 22, in <listcomp>
    _dataset_modules = [importlib.import_module(f'basicsr.data.{file_name}') for file_name in dataset_filenames]
  File "C:\Program Files\Python310\lib\importlib\__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "E:\File\Code\Python\Visual Studio\2022\CHZC\Software Cup\SoftwareCup PythonApplication\HELP\CodeFormer\basicsr\data\ffhq_blind_joint_dataset.py", line 12, in <module>
    from basicsr.data import gaussian_kernels as gaussian_kernels
ImportError: cannot import name 'gaussian_kernels' from partially initialized module 'basicsr.data' (most likely due to a circular import) (E:\File\Code\Python\Visual Studio\2022\CHZC\Software Cup\SoftwareCup PythonApplication\HELP\CodeFormer\basicsr\data\__init__.py)`

**Comment by AloneMonologue** [comment]
/CodeFormer/basicsr/data/ffhq_ blind_ joint_ The Gaussian kernels function in the dataset file cannot be imported 

![E1Z Q@2KB}W{6XZ3Q{)29WI](https://user-images.githubusercontent.com/54660648/233400611-feb58184-ce11-4052-a040-d3639aa06ed7.png)

**Comment by AloneMonologue** [comment]
/CodeFormer/basicsr/data/ffhq_blind_joint_dataset   The Gaussian kernels function in the file cannot be imported
![E1Z Q@2KB}W{6XZ3Q{)29WI](https://user-images.githubusercontent.com/54660648/233401301-e707cde3-fb60-466b-9ad3-c73bc2cb8790.png)
