### ISSUE TITLE
No module named 'gdown' error

### ISSUE THREAD

**Issue by Wimukthi** [sczhou/CodeFormer#21]
(codeformer) c:\CodeFormer>python inference_codeformer.py --w 0.7 --test_path \inputs\whole_imgs
Traceback (most recent call last):
  File "inference_codeformer.py", line 10, in <module>
    from facelib.utils.face_restoration_helper import FaceRestoreHelper
  File "c:\CodeFormer\facelib\utils\__init__.py", line 2, in <module>
    from .misc import img2tensor, load_file_from_url, download_pretrained_models, scandir
  File "c:\CodeFormer\facelib\utils\misc.py", line 7, in <module>
    import gdown
ModuleNotFoundError: No module named 'gdown'

**Comment by caacoe** [comment]
try 

`pip install gdown`

**Comment by Wimukthi** [comment]
Thank

> try
> 
> `pip install gdown`

Thank you that worked
