### ISSUE TITLE
TypeError: '<' not supported between instances of 'NoneType' and 'int'

### ISSUE THREAD

**Issue by sao-g** [sczhou/CodeFormer#290]
How does the inference work?? If i type in python inference_codeformer.py -w 0.7 --input_path [image folder]|[image path] then i get the following: '[image' is not recognized as an internal or external command,
operable program or batch file.

But if i type python inference_codeformer.py -w 0.7 --input_path boyz.jpg
Then it runs for a while but then says this:
```
 Processing: boyz.jpg
[ WARN:0@3.086] global loadsave.cpp:248 cv::findDecoder imread_('boyz.jpg'): can't open/read file: check file path/integrity
Traceback (most recent call last):
  File "inference_codeformer.py", line 188, in <module>
    face_helper.read_image(img)
  File "D:\CODING\CODEFORMER\CodeFormer-master\facelib\utils\face_restoration_helper.py", line 136, in read_image
    if np.max(img) < 256:  # 16-bit image
TypeError: '<' not supported between instances of 'NoneType' and 'int'
```

How am i supposed to run this, please? i'm a complete beginner and i have just finished installing the program.

**Comment by sao-g** [comment]
Oh never mind it worked. i had to put the full path name.
