### ISSUE TITLE
AttributeError: module 'PIL.Image' has no attribute 'ANTIALIAS'

### ISSUE THREAD

**Issue by ErfanBahramali** [sczhou/CodeFormer#294]
Error:
```
Traceback (most recent call last):
  File "scripts/crop_align_face.py", line 205, in <module>
    size_ = align_face(in_path, out_path)
  File "scripts/crop_align_face.py", line 177, in align_face
    img = img.resize((output_size, output_size), PIL.Image.ANTIALIAS)
AttributeError: module 'PIL.Image' has no attribute 'ANTIALIAS'

```
The problem is from Pillow version 10.0.0
`ANTIALIAS` was removed in Pillow 10.0.0 
Now you need to use `PIL.Image.LANCZOS` or `PIL.Image.Resampling.LANCZOS`
Or specify Pillow version in [requirements.txt](https://github.com/sczhou/CodeFormer/blob/master/requirements.txt)

`Pillow==9.5.0`

https://stackoverflow.com/questions/76616042/attributeerror-module-pil-image-has-no-attribute-antialias

**Comment by wonghin** [comment]
I am also facing this problem and have already followed the intruction

**Comment by wonghin** [comment]
Finally, try `pip install Pillow==9.4.0` in codeformer conda env. The problem will be solved
