### ISSUE TITLE
pre-trained VQGAN of 256*256 resolution ratio

### ISSUE THREAD

**Issue by create-li** [sczhou/CodeFormer#325]
It takes too long to train STAGE1(about 16days), so I want to add my own dataset for fine-tuning. Can you release pre-trained VQGAN model in STAGE1? Thanks a lot~

**Comment by franklydog** [comment]
> It takes too long to train STAGE1(about 16days), so I want to add my own dataset for fine-tuning. Can you release pre-trained VQGAN model in STAGE1? Thanks a lot~

hi,I want to train 256x256 also.But when the fisrt stage，I get erros as following：
Traceback (most recent call last):
  File "basicsr/train.py", line 225, in <module>
    train_pipeline(root_path)
  File "basicsr/train.py", line 186, in train_pipeline
    model.optimize_parameters(current_iter)
  File "/mnt/8T_disk/z/data/extra/virtual_person/CodeFormer/basicsr/models/vqgan_model.py", line 153, in optimize_parameters
    last_layer = self.net_g.module.generator.blocks[-1].weight
  File "/home/z/data/miniconda3/envs/codeformer/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1614, in __getattr__
    raise AttributeError("'{}' object has no attribute '{}'".format(
AttributeError: 'VQAutoEncoder' object has no attribute 'module'
Could you give me some hints？

**Comment by Genxb** [comment]
> > It takes too long to train STAGE1(about 16days), so I want to add my own dataset for fine-tuning. Can you release pre-trained VQGAN model in STAGE1? Thanks a lot~
> 
> hi,I want to train 256x256 also.But when the fisrt stage，I get erros as following： Traceback (most recent call last): File "basicsr/train.py", line 225, in train_pipeline(root_path) File "basicsr/train.py", line 186, in train_pipeline model.optimize_parameters(current_iter) File "/mnt/8T_disk/z/data/extra/virtual_person/CodeFormer/basicsr/models/vqgan_model.py", line 153, in optimize_parameters last_layer = self.net_g.module.generator.blocks[-1].weight File "/home/z/data/miniconda3/envs/codeformer/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1614, in **getattr** raise AttributeError("'{}' object has no attribute '{}'".format( AttributeError: 'VQAutoEncoder' object has no attribute 'module' Could you give me some hints？

Delete the attribute 'module'  in vqgan_model.py  line 153 
so the code should looks like
last_layer = self.net_g.generator.blocks[-1].weight

**Comment by volcanoxs** [comment]
I have encountered it too .How to modify the number of model blocks?
