### ISSUE TITLE
Help pleeease!

### ISSUE THREAD

**Issue by li-marigold** [sczhou/CodeFormer#329]
I'm a novice in coding and stuff) So I've made everythin' but... have this
What's that means?
Background upsampling: False, Face upsampling: False
[1/1] Processing: 8.jpg
[ WARN:0@9.075] global loadsave.cpp:248 cv::findDecoder imread_('E:\CodeFormer\inputs\whole_img\8.jpg'): can't open/read file: check file path/integrity
Traceback (most recent call last):
  File "inference_codeformer.py", line 188, in <module>
    face_helper.read_image(img)
  File "E:\CodeFormer\facelib\utils\face_restoration_helper.py", line 136, in read_image
    if np.max(img) > 256:  # 16-bit image
TypeError: '>' not supported between instances of 'NoneType' and 'int'

**Comment by Oil3** [comment]
It means that you are trying to compare two things that you can't compare,  "none", whicch iisn"rt a valuee of 0, but the absence of a value. Yoiu can fix it by saying none is 0 somewhere
