### ISSUE TITLE
KeyError: "No object named 'CodeFormer_basicsr' found in 'arch' registry!"

### ISSUE THREAD

**Issue by saba99** [sczhou/CodeFormer#365]
Name CodeFormer_basicsr is not found, use name: CodeFormer_basicsr_basicsr!
Traceback (most recent call last):
  File "/content/drive/MyDrive/dreamtalk/CodeFormer/inference_codeformer.py", line 135, in <module>
    net = ARCH_REGISTRY.get('CodeFormer_basicsr')(dim_embd=512, codebook_size=1024, n_head=8, n_layers=9, 
  File "/content/drive/MyDrive/dreamtalk/CodeFormer/basicsr/utils/registry.py", line 71, in get
    raise KeyError(f"No object named '{name}' found in '{self._name}' registry!")
KeyError: "No object named 'CodeFormer_basicsr' found in 'arch' registry!"
Traceback (most recent call last):
  File "/content/drive/MyDrive/dreamtalk/app.py", line 66, in pipe
    video =infer(audio_list, image_path,enhance,style,speech)
  File "/content/drive/MyDrive/dreamtalk/app.py", line 131, in infer
    enhanced_video_path = enhance_video_with_codeformer(input_file_for_codeformer)
  File "/content/drive/MyDrive/dreamtalk/app.py", line 101, in enhance_video_with_codeformer
    execute_command(command)
  File "/content/drive/MyDrive/dreamtalk/app.py", line 83, in execute_command
    subprocess.run(command, check=True)
  File "/usr/lib/python3.10/subprocess.py", line 526, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['python', '/content/drive/MyDrive/dreamtalk/CodeFormer/inference_codeformer.py', '--bg_upsampler', 'realesrgan', '--face_upsample', '-w', '1.0', '--input_path', '/content/drive/MyDrive/dreamtalk/output_video/lipsynced_result_20240330154241.mp4']' returned non-zero exit status 1.

**Comment by jasuriy** [comment]
@saba99 I got the same error. did you fix it ? please let me know if you did.
