### ISSUE TITLE
python scripts/download_pretrained_models.py CodeFormer - issue

### ISSUE THREAD

**Issue by Eddie-cjz** [sczhou/CodeFormer#382]
![c0fdec94-a9fd-4d0d-9363-5c884cc4bf93](https://github.com/sczhou/CodeFormer/assets/121542910/52096ad0-9777-4959-9224-5d12371c58c4)

没有完全下载好，直接跳出来，重新输入命令没有任何反应，怎么办？
I don't download it completely, just jump out and re-enter the command without any response. What should I do ？

**Comment by Eddie-cjz** [comment]
(codeformer-python310) w:\software\github_clone_items\CodeFormer>python inference_codeformer.py -w 0.5 --has_aligned --input_path W:\software\github_clone_items\CodeFormer\inputs\cropped_faces
Traceback (most recent call last):
  File "w:\software\github_clone_items\CodeFormer\inference_codeformer.py", line 141, in <module>
    checkpoint = torch.load(ckpt_path)['params_ema']
  File "W:\software\install\anaconda3\envs\codeformer-python310\lib\site-packages\torch\serialization.py", line 797, in load
    with _open_zipfile_reader(opened_file) as opened_zipfile:
  File "W:\software\install\anaconda3\envs\codeformer-python310\lib\site-packages\torch\serialization.py", line 283, in __init__
    super().__init__(torch._C.PyTorchFileReader(name_or_buffer))
**RuntimeError: PytorchStreamReader failed reading zip archive: failed finding central directory**

运行命令的时候出现这样的报错，应该是模型因为网络原因未完全下载导致的，我想重新下载，应该怎么做？我找不到这个模型的路径
