### ISSUE TITLE
请问为啥我会一直在出现RuntimeError: Numpy is not available的错误呢，我尝试降级但是会报错....

### ISSUE THREAD

**Issue by pawn144454** [sczhou/CodeFormer#389]
[1/90] Processing: test_000000
Traceback (most recent call last):
  File "C:\Users\14445\CodeFormer\inference_codeformer.py", line 190, in <module>
    num_det_faces = face_helper.get_face_landmarks_5(
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\14445\CodeFormer\facelib\utils\face_restoration_helper.py", line 217, in get_face_landmarks_5
    bboxes = self.face_detector.detect_faces(input_img)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\14445\CodeFormer\facelib\detection\retinaface\retinaface.py", line 205, in detect_faces
    image, self.resize = self.transform(image, use_origin_size)
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\14445\CodeFormer\facelib\detection\retinaface\retinaface.py", line 190, in transform
    image = torch.from_numpy(image).unsqueeze(0)
            ^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: Numpy is not available

请问有没有什么解决办法呢？

**Comment by pawn144454** [comment]
降级后成功解决了
