### ISSUE TITLE
For videos

### ISSUE THREAD

**Issue by Meta-Mahdi** [sczhou/CodeFormer#60]
Hi
I hope that you be great in your life
I want to know how to use CodeForme for videos? if really it is possible can you tell exactly how?
It is really necessary for me...

**Comment by sczhou** [comment]
You can use the following command for the video enhancement: 

```
python inference_codeformer.py --bg_upsampler realesrgan --face_upsample -w 1.0 --input_path  your_video_path.mp4 --save_video_fps 24
```
You can set frame rate of saved video via '--save_video_fps 24'

All commands can be also found in the [README.md](https://github.com/sczhou/CodeFormer/blob/master/README.md) file.

**Comment by vantablackndark** [comment]
Hi, I did try this but I always get an error. Any chance someone knows what wrong i am doing?

E:\AI\CodeFormer\CodeFormer>python inference_codeformer.py --bg_upsampler realesrgan --face_upsample -w 1.0 --input_path  01.mp4 --save_video_fps 24
Face detection model: retinaface_resnet50
Background upsampling: True, Face upsampling: True
Traceback (most recent call last):
  File "E:\AI\CodeFormer\CodeFormer\inference_codeformer.py", line 251, in <module>
    h, w = video_frames[0].shape[:2]
IndexError: list index out of range

**Comment by newchcoder** [comment]
> python inference_codeformer.py --bg_upsampler realesrgan --face_upsampl

After running this command, there are nothing in result methods. Ffmepg has already installed but still not working. I didn't have the slightest idea……

**Comment by 9cat** [comment]
I got all the PNGs , and when saving to video, it get killed by the system.
I am trying to using to swap to see if just because the memory.

**Comment by WenchenLi** [comment]
> I got all the PNGs , and when saving to video, it get killed by the system. I am trying to using to swap to see if just because the memory.

save here

**Comment by hengsleep** [comment]
Traceback (most recent call last):
  File "C:\Users\***\CodeFormer\inference_codeformer.py", line 111, in <module>
    raise FileNotFoundError("\nInput file is not found.")
FileNotFoundError:
Input file is not found.
---i have already install ffmpeg,and i am sure that my file path is correct,but when i start the video in the windows,why it says "filenotfounderror"?

**Comment by tayiu** [comment]
Inference_codeformer.py: error: unrecognized arguments: C:\Users\***\CodeFormer\inputs\***
--- What happened?

**Comment by lcloveyou** [comment]
> I got all the PNGs , and when saving to video, it get killed by the system. I am trying to using to swap to see if just because the memory.

I also encountered this problem, have you solved it, brother
