### ISSUE TITLE
ModuleNotFoundError: No module named 'basicsr.version'

### ISSUE THREAD

**Issue by ArtemChirakhov** [sczhou/CodeFormer#84]
While trying to run the web-user.bat in stable diffusion i get this:

Python 3.10.6 (tags/v3.10.6:9c7b4bd, Aug 1 2022, 21:53:49) [MSC v.1932 64 bit (AMD64)]
Commit hash: https://github.com/AUTOMATIC1111/stable-diffusion-webui/commit/685f9631b56ff8bd43bce24ff5ce0f9a0e9af490
Installing requirements for Web UI
Launching Web UI with arguments:
Traceback (most recent call last):
File "C:\Users\XXX\PycharmProjects\stable-diffusion-webui\launch.py", line 295, in
start()
File "C:\Users\XXX\PycharmProjects\stable-diffusion-webui\launch.py", line 286, in start
import webui
File "C:\Users\XXX\PycharmProjects\stable-diffusion-webui\webui.py", line 11, in
from modules.call_queue import wrap_queued_call, queue_lock, wrap_gradio_gpu_call
File "C:\Users\achir\PycharmProjects\stable-diffusion-webui\modules\call_queue.py", line 7, in
from modules import shared
File "C:\Users\XXX\PycharmProjects\stable-diffusion-webui\modules\shared.py", line 12, in
import modules.interrogate
File "C:\Users\XXX\PycharmProjects\stable-diffusion-webui\modules\interrogate.py", line 13, in
from modules import devices, paths, lowvram, modelloader
File "C:\Users\XXX\PycharmProjects\stable-diffusion-webui\modules\modelloader.py", line 7, in
from basicsr.utils.download_util import load_file_from_url
File "C:\Users\XXX\PycharmProjects\stable-diffusion-webui\repositories\CodeFormer\basicsr_init_.py", line 11, in
from .version import gitsha, version
ModuleNotFoundError: No module named 'basicsr.version'

someone answered to my issue and said i should post here an issue here because "This is a codeformer issue not a SD webui issue."

**Comment by sczhou** [comment]
Hi, CodeFormer doesn't have this issue, you may check if you install the basicsr successfully
https://github.com/sczhou/CodeFormer#dependencies-and-installation
`python basicsr/setup.py develop`

**Comment by xiao12mm** [comment]
> Hi, CodeFormer doesn't have this issue, you may check if you install the basicsr successfully https://github.com/sczhou/CodeFormer#dependencies-and-installation `python basicsr/setup.py develop`

See here I know the reason, you rewrite this library, and write in the description, but this way in other projects rarely, so that many people here do not understand, the correct approach is to uninstall the basicsr library, and install the library you rewrite？

**Comment by YABIJIU** [comment]
正确安装basicsr之后，在你的codeformer项目里面会有两个basicsr的文件夹，一个在codeformer文件夹目录下，还有一个在..、CodeFormer-master\venv\Lib\site-packages下，在第二个basicsr中找到version.py文件，复制，然后粘贴到第一个basicsr文件夹里面，问题就解决了，就是缺个version.py的文件而已。我是个菜鸟，不懂这个开源项目为啥会自己创建个basicsr，并且少了一个重要的文件。
